[2024-10-20 12:43:25,288: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-10-20 12:43:25,288: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-20 12:43:25,288: INFO: common: created directory at: data\raw]
[2024-10-20 12:43:27,736: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-10-20 12:43:27,736: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-10-20 12:43:55,089: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-10-20 12:43:55,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-10-20 12:43:55,118: INFO: common: created directory at: data\raw]
[2024-10-20 12:43:56,158: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-10-20 12:43:56,158: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-10 22:12:21,450: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-10 22:12:21,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-10 22:12:21,466: INFO: common: created directory at: data\raw]
[2024-11-10 22:12:27,885: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-10 22:12:27,885: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-10 22:12:27,885: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-10 22:12:27,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-10 22:12:27,885: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-10 22:12:27,900: ERROR: data_preprocessing: Error loading data: [Errno 2] No such file or directory: 'data\\raw\\stock_data.csv']
[2024-11-10 22:12:27,900: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-18 16:44:30,074: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 16:44:30,074: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 16:44:30,074: INFO: common: created directory at: data\raw]
[2024-11-18 16:44:31,338: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 16:44:31,338: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 16:44:31,338: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 16:44:31,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 16:44:31,338: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-18 16:44:31,338: ERROR: data_preprocessing: Error loading data: [Errno 2] No such file or directory: 'data\\raw\\stock_data.csv']
[2024-11-18 16:44:31,338: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-18 16:52:59,994: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 16:52:59,994: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 16:52:59,994: INFO: common: created directory at: data\raw]
[2024-11-18 16:53:00,572: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 16:53:00,572: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 16:53:00,572: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 16:53:00,572: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 16:53:00,587: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-18 16:53:00,587: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-18 17:02:10,324: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 17:02:10,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:02:10,324: INFO: common: created directory at: data\raw]
[2024-11-18 17:02:11,024: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 17:02:11,024: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 17:02:11,024: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 17:02:11,039: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:02:11,039: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-18 17:02:11,055: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-18 17:02:54,463: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 17:02:54,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:02:54,463: INFO: common: created directory at: data\raw]
[2024-11-18 17:02:55,057: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 17:02:55,057: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 17:02:55,057: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 17:02:55,057: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:02:55,057: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-18 17:02:55,057: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-18 17:02:55,057: ERROR: data_preprocessing: Error handling missing values: 'DataPreprocessingConfig' object has no attribute 'missing_values_strategy']
[2024-11-18 17:02:55,057: ERROR: data_preprocessing: Error applying transformations: 'NoneType' object is not subscriptable]
[2024-11-18 17:02:55,057: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-18 17:04:19,318: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 17:04:19,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:04:19,333: INFO: common: created directory at: data\raw]
[2024-11-18 17:04:19,880: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 17:04:19,880: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 17:04:19,880: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 17:04:19,880: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:04:19,880: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-18 17:04:19,880: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-18 17:04:19,880: ERROR: data_preprocessing: Error handling missing values: 'DataPreprocessingConfig' object has no attribute 'missing_values_strategy']
[2024-11-18 17:04:19,880: ERROR: data_preprocessing: Error applying transformations: 'NoneType' object is not subscriptable]
[2024-11-18 17:04:19,880: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-18 17:06:47,043: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 17:06:47,059: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:06:47,059: INFO: common: created directory at: data\raw]
[2024-11-18 17:06:52,043: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 17:06:52,043: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 17:06:52,043: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 17:06:52,043: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:10:43,957: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 17:10:43,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:10:43,957: INFO: common: created directory at: data\raw]
[2024-11-18 17:10:45,785: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 17:10:45,785: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 17:10:45,785: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 17:10:45,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:10:45,785: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-18 17:10:45,785: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-18 17:10:45,800: ERROR: data_preprocessing: Error handling missing values: Could not convert ['2024-10-18 19:59:002024-10-18 19:56:002024-10-18 19:54:002024-10-18 19:50:002024-10-18 19:46:002024-10-18 19:45:002024-10-18 19:43:002024-10-18 19:33:002024-10-18 19:32:002024-10-18 19:14:002024-10-18 19:12:002024-10-18 19:07:002024-10-18 19:04:002024-10-18 19:00:002024-10-18 18:57:002024-10-18 18:56:002024-10-18 18:46:002024-10-18 18:45:002024-10-18 18:33:002024-10-18 18:30:002024-10-18 18:28:002024-10-18 18:17:002024-10-18 18:16:002024-10-18 18:15:002024-10-18 18:09:002024-10-18 17:59:002024-10-18 17:50:002024-10-18 17:49:002024-10-18 17:27:002024-10-18 17:26:002024-10-18 17:25:002024-10-18 17:20:002024-10-18 17:18:002024-10-18 17:17:002024-10-18 17:16:002024-10-18 17:12:002024-10-18 17:00:002024-10-18 16:59:002024-10-18 16:58:002024-10-18 16:55:002024-10-18 16:54:002024-10-18 16:53:002024-10-18 16:50:002024-10-18 16:48:002024-10-18 16:47:002024-10-18 16:46:002024-10-18 16:44:002024-10-18 16:40:002024-10-18 16:39:002024-10-18 16:36:002024-10-18 16:34:002024-10-18 16:33:002024-10-18 16:31:002024-10-18 16:30:002024-10-18 16:27:002024-10-18 16:23:002024-10-18 16:21:002024-10-18 16:20:002024-10-18 16:19:002024-10-18 16:18:002024-10-18 16:17:002024-10-18 16:16:002024-10-18 16:15:002024-10-18 16:14:002024-10-18 16:13:002024-10-18 16:12:002024-10-18 16:10:002024-10-18 16:09:002024-10-18 16:06:002024-10-18 16:05:002024-10-18 16:04:002024-10-18 16:03:002024-10-18 16:02:002024-10-18 16:01:002024-10-18 16:00:002024-10-18 15:59:002024-10-18 15:58:002024-10-18 15:57:002024-10-18 15:56:002024-10-18 15:55:002024-10-18 15:54:002024-10-18 15:53:002024-10-18 15:52:002024-10-18 15:51:002024-10-18 15:50:002024-10-18 15:49:002024-10-18 15:48:002024-10-18 15:47:002024-10-18 15:46:002024-10-18 15:45:002024-10-18 15:44:002024-10-18 15:43:002024-10-18 15:42:002024-10-18 15:41:002024-10-18 15:40:002024-10-18 15:39:002024-10-18 15:38:002024-10-18 15:37:002024-10-18 15:36:002024-10-18 15:35:00'] to numeric]
[2024-11-18 17:10:45,800: ERROR: data_preprocessing: Error applying transformations: 'NoneType' object is not subscriptable]
[2024-11-18 17:10:45,800: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-18 17:21:45,414: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 17:21:45,430: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:21:45,430: INFO: common: created directory at: data\raw]
[2024-11-18 17:21:57,118: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 17:21:57,118: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 17:21:57,118: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 17:21:57,118: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:22:23,069: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 17:22:23,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:22:23,069: INFO: common: created directory at: data\raw]
[2024-11-18 17:22:32,852: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 17:22:32,852: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 17:22:32,852: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 17:22:32,852: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 17:22:32,867: INFO: common: created directory at: data\processed\preprocessed_stock_data.csv]
[2024-11-18 17:22:32,883: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-18 17:22:32,883: INFO: data_preprocessing: Applied transformations to data]
[2024-11-18 17:22:32,898: INFO: data_preprocessing: Processed data saved to data\processed\preprocessed_stock_data.csv\processed_stock_data.csv]
[2024-11-18 17:22:32,898: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-18 20:38:21,672: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-18 20:38:21,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 20:38:21,692: INFO: common: created directory at: data\raw]
[2024-11-18 20:38:24,262: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-18 20:38:24,262: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-18 20:38:24,262: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-18 20:38:24,277: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-18 20:38:24,277: INFO: common: created directory at: data\processed]
[2024-11-18 20:38:24,312: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-18 20:38:24,354: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-18 20:38:24,372: INFO: data_preprocessing: Applied transformations to data]
[2024-11-18 20:38:24,392: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-18 20:38:24,392: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:35:52,298: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:35:52,314: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:35:52,314: INFO: common: created directory at: data\raw]
[2024-11-19 16:35:52,959: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:35:52,959: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:35:52,959: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:35:52,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:35:52,963: INFO: common: created directory at: data\processed]
[2024-11-19 16:35:52,977: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:35:52,982: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:35:52,982: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:35:52,982: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:35:52,982: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:35:52,982: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:36:27,594: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:36:27,594: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:36:27,594: INFO: common: created directory at: data\raw]
[2024-11-19 16:36:28,063: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:36:28,063: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:36:28,063: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:36:28,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:36:28,079: INFO: common: created directory at: data\processed]
[2024-11-19 16:36:28,079: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:36:28,079: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:36:28,079: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:36:28,094: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:36:28,094: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:36:28,094: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:36:28,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:40:53,689: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:40:53,705: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:40:53,705: INFO: common: created directory at: data\raw]
[2024-11-19 16:40:55,283: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:40:55,283: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:40:55,283: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:40:55,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:40:55,283: INFO: common: created directory at: data\processed]
[2024-11-19 16:40:55,283: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:40:55,283: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:40:55,299: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:40:55,299: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:40:55,299: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:40:55,299: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:40:55,299: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:47:11,334: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:47:11,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:47:11,334: INFO: common: created directory at: data\raw]
[2024-11-19 16:47:11,897: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:47:11,897: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:47:11,897: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:47:11,897: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:47:11,897: INFO: common: created directory at: data\processed]
[2024-11-19 16:47:11,897: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:47:11,897: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:47:11,897: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:47:11,912: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:47:11,912: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:47:11,912: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:47:11,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:48:14,514: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:48:14,514: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:48:14,514: INFO: common: created directory at: data\raw]
[2024-11-19 16:48:15,061: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:48:15,061: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:48:15,061: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:48:15,076: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:48:15,076: INFO: common: created directory at: data\processed]
[2024-11-19 16:48:15,076: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:48:15,076: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:48:15,092: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:48:15,092: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:48:15,092: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:48:15,092: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:48:15,092: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:49:05,243: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:49:05,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:49:05,243: INFO: common: created directory at: data\raw]
[2024-11-19 16:49:05,744: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:49:05,744: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:49:05,744: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:49:05,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:49:05,744: INFO: common: created directory at: data\processed]
[2024-11-19 16:49:05,744: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:49:05,759: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:49:05,759: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:49:05,759: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:49:05,759: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:49:05,759: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:49:05,759: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:50:00,587: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:50:00,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:50:00,587: INFO: common: created directory at: data\raw]
[2024-11-19 16:50:01,087: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:50:01,087: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:50:01,087: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:50:01,087: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:50:01,087: INFO: common: created directory at: data\processed]
[2024-11-19 16:50:01,087: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:50:01,087: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:50:01,087: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:50:01,102: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:50:01,102: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:50:01,102: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:50:01,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:50:28,177: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:50:28,177: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:50:28,177: INFO: common: created directory at: data\raw]
[2024-11-19 16:50:28,661: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:50:28,661: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:50:28,661: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:50:28,677: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:50:28,677: INFO: common: created directory at: data\processed]
[2024-11-19 16:50:28,677: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:50:28,692: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:50:28,692: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:50:28,692: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:50:28,692: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:50:28,692: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:50:28,708: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:55:19,951: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:55:19,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:55:19,951: INFO: common: created directory at: data\raw]
[2024-11-19 16:55:20,514: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:55:20,529: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:55:20,529: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:55:20,529: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:55:20,529: INFO: common: created directory at: data\processed]
[2024-11-19 16:55:20,529: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:55:20,529: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:55:20,545: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:55:20,545: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:55:20,545: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:55:20,545: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:55:54,511: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 16:55:54,527: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:55:54,527: INFO: common: created directory at: data\raw]
[2024-11-19 16:55:55,567: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 16:55:55,567: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 16:55:55,567: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 16:55:55,567: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:55:55,567: INFO: common: created directory at: data\processed]
[2024-11-19 16:55:55,567: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 16:55:55,582: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 16:55:55,582: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 16:55:55,582: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 16:55:55,582: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 16:55:55,582: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 16:55:55,582: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 16:55:55,582: ERROR: data_validate: Error loading data: [Errno 2] No such file or directory: 'data\\processed\\preprocessed_stock_data.csv']
[2024-11-19 16:55:55,582: ERROR: data_validate: Error running the validation pipeline: [Errno 2] No such file or directory: 'data\\processed\\preprocessed_stock_data.csv']
[2024-11-19 17:09:40,555: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 17:09:40,571: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 17:09:40,571: INFO: common: created directory at: data\raw]
[2024-11-19 17:09:41,165: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 17:09:41,165: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 17:09:41,165: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 17:09:41,165: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 17:09:41,165: INFO: common: created directory at: data\processed]
[2024-11-19 17:09:41,180: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 17:09:41,180: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 17:09:41,180: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 17:09:41,180: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 17:09:41,180: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 17:09:41,180: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 17:09:41,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 17:09:41,212: INFO: data_validate: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-19 17:09:41,212: ERROR: data_validate: Data contains missing values.]
[2024-11-19 17:09:41,212: ERROR: data_validate: Data validation failed.]
[2024-11-19 17:30:57,231: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 17:30:57,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 17:30:57,231: INFO: common: created directory at: data\raw]
[2024-11-19 17:30:57,637: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 17:30:57,637: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 17:30:57,637: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 17:30:57,637: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 17:30:57,637: INFO: common: created directory at: data\processed]
[2024-11-19 17:30:57,637: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 17:30:57,653: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 17:30:57,653: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 17:30:57,668: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 17:30:57,668: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 17:30:57,668: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 17:30:57,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 17:30:57,684: INFO: data_validate: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-19 17:30:57,684: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-19 17:30:57,684: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-19 17:30:57,684: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-19 20:16:24,234: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 20:16:24,265: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:16:24,265: INFO: common: created directory at: data\raw]
[2024-11-19 20:16:25,125: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 20:16:25,125: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 20:16:25,125: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 20:16:25,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:16:25,141: INFO: common: created directory at: data\processed]
[2024-11-19 20:16:25,157: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 20:16:25,188: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 20:16:25,219: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 20:16:25,235: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 20:16:25,235: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 20:16:25,235: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 20:16:25,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:16:25,298: INFO: data_validate: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-19 20:16:25,314: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-19 20:16:25,314: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-19 20:16:25,314: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-19 20:31:47,767: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 20:31:47,782: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:31:47,782: INFO: common: created directory at: data\raw]
[2024-11-19 20:31:48,662: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 20:31:48,662: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 20:31:48,662: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 20:31:48,662: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:31:48,662: INFO: common: created directory at: data\processed]
[2024-11-19 20:31:48,678: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 20:31:48,695: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 20:31:48,695: INFO: data_preprocessing: Applied transformations to data]
[2024-11-19 20:31:48,709: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-19 20:31:48,709: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 20:31:48,709: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 20:31:48,709: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:31:48,741: INFO: data_validate: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-19 20:31:48,741: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-19 20:31:48,741: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-19 20:31:48,741: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-19 20:38:55,354: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 20:38:55,370: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:38:55,370: INFO: common: created directory at: data\raw]
[2024-11-19 20:38:56,191: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 20:38:56,191: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 20:38:56,191: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 20:38:56,203: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:38:56,203: INFO: common: created directory at: data\processed]
[2024-11-19 20:38:56,219: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 20:38:56,234: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 20:38:56,250: ERROR: data_preprocessing: Error applying transformations: name 'data' is not defined]
[2024-11-19 20:38:56,250: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 20:38:56,250: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 20:38:56,266: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:38:56,266: INFO: data_validate: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-19 20:38:56,281: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-19 20:38:56,281: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-19 20:38:56,281: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-19 20:39:40,715: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-19 20:39:40,738: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:39:40,738: INFO: common: created directory at: data\raw]
[2024-11-19 20:39:41,446: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-19 20:39:41,446: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-19 20:39:41,446: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-19 20:39:41,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:39:41,454: INFO: common: created directory at: data\processed]
[2024-11-19 20:39:41,454: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-19 20:39:41,454: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-19 20:39:41,470: ERROR: data_preprocessing: Error applying transformations: name 'data' is not defined]
[2024-11-19 20:39:41,470: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-19 20:39:41,470: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-19 20:39:41,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-19 20:39:41,486: INFO: data_validate: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-19 20:39:41,486: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-19 20:39:41,486: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-19 20:39:41,486: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 12:44:36,348: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:45:38,468: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:46:24,860: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:46:53,525: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:48:35,769: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:48:35,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:48:35,801: INFO: common: created directory at: data\raw]
[2024-11-22 12:48:36,488: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 12:48:36,488: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 12:48:36,503: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 12:48:36,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:48:36,519: INFO: common: created directory at: data\processed]
[2024-11-22 12:48:36,535: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-22 12:48:36,566: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 12:48:36,597: ERROR: data_preprocessing: Error applying transformations: name 'data' is not defined]
[2024-11-22 12:48:36,597: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 12:48:36,597: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 12:48:36,613: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:50:11,074: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:50:11,081: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:50:11,084: INFO: common: created directory at: data\raw]
[2024-11-22 12:50:15,606: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 12:50:15,606: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 12:50:15,606: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 12:50:15,622: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:50:15,622: INFO: common: created directory at: data\processed]
[2024-11-22 12:50:15,653: INFO: data_preprocessing: Data loaded from data\raw\IBM_stock_data.csv]
[2024-11-22 12:50:15,700: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 12:50:15,731: ERROR: data_preprocessing: Error applying transformations: name 'data' is not defined]
[2024-11-22 12:50:15,731: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 12:50:15,731: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 12:50:15,747: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:50:15,763: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 12:50:15,763: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 12:52:04,574: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:52:04,589: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:52:04,589: INFO: common: created directory at: data]
[2024-11-22 12:52:05,199: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 12:52:05,199: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 12:52:05,199: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 12:52:05,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:52:05,199: INFO: common: created directory at: data\processed]
[2024-11-22 12:52:05,199: ERROR: data_preprocessing: Error loading data: [Errno 13] Permission denied: 'data\\raw']
[2024-11-22 12:52:05,199: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 12:52:05,199: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 12:52:05,214: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:52:05,214: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 12:52:05,214: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 12:52:44,353: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 12:52:44,353: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:52:44,353: INFO: common: created directory at: data]
[2024-11-22 12:52:44,916: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 12:52:44,916: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 12:52:44,916: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 12:52:44,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:52:44,931: INFO: common: created directory at: data\processed]
[2024-11-22 12:52:44,931: ERROR: data_preprocessing: Error loading data: [Errno 2] No such file or directory: 'data\\raw']
[2024-11-22 12:52:44,931: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 12:52:44,931: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 12:52:44,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 12:52:44,947: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 12:52:44,947: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:02:22,954: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:02:22,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:02:22,954: INFO: common: created directory at: data]
[2024-11-22 13:02:23,782: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 13:02:23,782: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 13:02:23,782: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 13:02:23,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:02:23,798: INFO: common: created directory at: data\processed]
[2024-11-22 13:02:23,798: ERROR: data_preprocessing: Error loading data: [Errno 2] No such file or directory: 'data\\raw']
[2024-11-22 13:02:23,798: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 13:02:23,798: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 13:02:23,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:02:23,813: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:02:23,813: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:02:39,559: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:02:39,559: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:02:39,559: INFO: common: created directory at: data]
[2024-11-22 13:02:40,154: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 13:02:40,154: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 13:02:40,154: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 13:02:40,169: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:02:40,169: INFO: common: created directory at: data\processed]
[2024-11-22 13:02:40,184: ERROR: data_preprocessing: Error loading data: [Errno 2] No such file or directory: 'data\\raw']
[2024-11-22 13:02:40,184: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 13:02:40,188: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 13:02:40,202: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:02:40,205: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:02:40,205: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:03:02,959: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:03:02,959: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:03:02,959: INFO: common: created directory at: data]
[2024-11-22 13:03:03,912: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 13:03:03,912: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 13:03:15,794: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:03:15,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:03:15,794: INFO: common: created directory at: data]
[2024-11-22 13:03:16,388: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 13:03:16,388: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 13:15:37,972: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:15:37,989: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:17:14,640: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:17:14,656: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:17:14,656: INFO: common: created directory at: data\raw]
[2024-11-22 13:17:15,365: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 13:17:15,365: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 13:17:15,365: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 13:17:15,365: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:17:15,365: INFO: common: created directory at: data\processed]
[2024-11-22 13:17:15,365: ERROR: data_preprocessing: Error loading data: [Errno 13] Permission denied: 'data\\raw']
[2024-11-22 13:17:15,365: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 13:17:15,365: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 13:17:15,382: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:17:15,382: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:17:15,382: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:21:02,398: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:21:02,413: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:21:02,413: INFO: common: created directory at: data\raw]
[2024-11-22 13:21:03,609: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 13:21:03,609: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 13:21:03,609: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 13:21:03,625: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:21:03,625: INFO: common: created directory at: data\processed]
[2024-11-22 13:21:03,625: ERROR: data_preprocessing: Error loading data: [Errno 13] Permission denied: 'data\\raw']
[2024-11-22 13:21:03,625: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 13:21:03,625: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 13:21:03,625: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:21:03,625: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:21:03,640: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 13:24:15,605: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 13:24:15,620: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 13:24:15,620: INFO: common: created directory at: data\raw]
[2024-11-22 14:08:08,948: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:08:08,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:08:08,963: INFO: common: created directory at: data\raw]
[2024-11-22 14:14:13,993: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:14:13,993: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:14:13,993: INFO: common: created directory at: data\raw]
[2024-11-22 14:14:14,759: ERROR: data_ingestion: Time series data not found for interval 1min]
[2024-11-22 14:14:14,759: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 14:14:33,331: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:14:33,346: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:14:33,346: INFO: common: created directory at: data\raw]
[2024-11-22 14:14:34,041: ERROR: data_ingestion: Time series data not found for interval 1min]
[2024-11-22 14:14:34,041: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 14:19:06,560: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:19:06,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:19:06,560: INFO: common: created directory at: data\raw]
[2024-11-22 14:22:02,674: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:22:02,676: INFO: common: created directory at: data]
[2024-11-22 14:22:04,861: INFO: 406052314: Raw data saved to data\IBM_stock_data.csv]
[2024-11-22 14:24:55,951: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:24:55,967: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:24:55,967: INFO: common: created directory at: data\raw]
[2024-11-22 14:24:56,719: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 14:24:56,719: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 14:25:58,724: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:25:58,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:25:58,740: INFO: common: created directory at: data]
[2024-11-22 14:25:59,486: ERROR: data_ingestion: Time Series data not found in response]
[2024-11-22 14:25:59,486: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 14:32:28,182: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:32:28,184: INFO: common: created directory at: data]
[2024-11-22 14:40:07,691: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:40:07,710: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:40:07,800: INFO: common: created directory at: data]
[2024-11-22 14:41:52,595: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:41:52,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:41:52,610: INFO: common: created directory at: data]
[2024-11-22 14:41:53,485: INFO: data_ingestion: Data saved as JSON to data\IBM_stock_data.json]
[2024-11-22 14:41:53,485: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 14:59:47,450: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 14:59:47,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 14:59:47,466: INFO: common: created directory at: data]
[2024-11-22 14:59:50,731: INFO: data_ingestion: Data saved as JSON to data\IBM_stock_data.json]
[2024-11-22 14:59:50,731: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:01:14,081: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:01:14,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:01:14,096: INFO: common: created directory at: data]
[2024-11-22 15:01:16,457: INFO: data_ingestion: Raw data saved to data\IBM_stock_data.csv]
[2024-11-22 15:01:16,472: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:01:16,472: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:01:16,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:01:16,472: INFO: common: created directory at: data\processed]
[2024-11-22 15:01:16,472: ERROR: data_preprocessing: Error loading data: [Errno 2] No such file or directory: 'data\\raw']
[2024-11-22 15:01:16,472: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:01:16,472: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 15:01:16,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:01:16,472: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:01:16,472: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:03:08,745: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:03:08,745: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:03:08,745: INFO: common: created directory at: data\raw]
[2024-11-22 15:03:10,884: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 15:03:10,884: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:03:10,884: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:03:10,884: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:03:10,884: INFO: common: created directory at: data\processed]
[2024-11-22 15:03:10,884: ERROR: data_preprocessing: Error loading data: [Errno 13] Permission denied: 'data\\raw']
[2024-11-22 15:03:10,884: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:03:10,884: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 15:03:10,899: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:03:10,899: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:03:10,899: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:13:16,889: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:13:16,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:13:16,904: INFO: common: created directory at: data\raw\IBM_stock_data.csv]
[2024-11-22 15:13:19,585: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv\IBM_stock_data.csv]
[2024-11-22 15:13:19,601: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:13:19,601: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:13:19,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:13:19,601: INFO: common: created directory at: data\processed]
[2024-11-22 15:13:19,601: ERROR: data_preprocessing: Error loading data: [Errno 13] Permission denied: 'data\\raw\\IBM_stock_data.csv']
[2024-11-22 15:13:19,601: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:13:19,601: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 15:13:19,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:13:19,601: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:13:19,601: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:24:54,506: ERROR: 2956780545: Error loading data: type object 'DataPreprocessingConfig' has no attribute 'input_csv_file']
[2024-11-22 15:27:07,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:27:07,041: INFO: common: created directory at: data\processed]
[2024-11-22 15:27:46,650: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:27:46,652: INFO: common: created directory at: data\processed]
[2024-11-22 15:27:46,654: ERROR: 2956780545: Error loading data: [Errno 2] No such file or directory: 'data\\raw']
[2024-11-22 15:28:29,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:28:29,611: INFO: common: created directory at: data\processed]
[2024-11-22 15:28:29,612: ERROR: 2956780545: Error loading data: [Errno 2] No such file or directory: 'data\\raw']
[2024-11-22 15:31:15,889: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:31:15,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:31:15,904: INFO: common: created directory at: data\raw]
[2024-11-22 15:31:18,752: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 15:31:18,756: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:31:18,757: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:31:18,761: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:31:18,762: INFO: common: created directory at: data\processed]
[2024-11-22 15:31:18,762: ERROR: data_preprocessing: Error loading data: [Errno 13] Permission denied: 'data\\raw']
[2024-11-22 15:31:18,762: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:31:18,763: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 15:31:18,765: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:31:18,765: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:31:18,767: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:31:28,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:31:28,653: INFO: common: created directory at: data\processed]
[2024-11-22 15:31:28,655: ERROR: 2956780545: Error loading data: [Errno 13] Permission denied: 'data\\raw']
[2024-11-22 15:32:03,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:32:03,875: INFO: common: created directory at: data\processed]
[2024-11-22 15:32:03,906: INFO: 1333392615: Data loaded from data\raw]
[2024-11-22 15:33:56,392: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:33:56,392: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:33:56,392: INFO: common: created directory at: data\raw]
[2024-11-22 15:34:00,636: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 15:34:00,636: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:34:00,636: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:34:00,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:34:00,651: INFO: common: created directory at: data\processed]
[2024-11-22 15:34:00,651: ERROR: data_preprocessing: Error loading data: [Errno 13] Permission denied: 'data\\raw']
[2024-11-22 15:34:00,651: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:34:00,651: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 15:34:00,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:34:00,651: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:34:00,651: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:34:43,263: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:34:43,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:34:43,263: INFO: common: created directory at: data\raw]
[2024-11-22 15:34:45,950: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 15:34:45,950: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:34:45,950: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:34:45,950: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:34:45,950: INFO: common: created directory at: data\processed]
[2024-11-22 15:34:45,981: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 15:34:45,997: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 15:34:45,997: ERROR: data_preprocessing: Error applying transformations: name 'data' is not defined]
[2024-11-22 15:34:45,997: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:34:45,997: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 15:34:45,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:34:45,997: ERROR: data_validate: Error loading data: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:34:45,997: ERROR: data_validate: Error running the validation pipeline: [Errno 13] Permission denied: 'data\\processed']
[2024-11-22 15:35:24,472: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:35:24,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:35:24,472: INFO: common: created directory at: data\raw]
[2024-11-22 15:35:27,269: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 15:35:27,269: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:35:27,269: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:35:27,285: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:35:27,285: INFO: common: created directory at: data\processed]
[2024-11-22 15:35:27,300: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 15:35:27,316: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 15:35:27,316: ERROR: data_preprocessing: Error applying transformations: name 'data' is not defined]
[2024-11-22 15:35:27,316: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:36:41,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:36:41,874: INFO: common: created directory at: data\processed]
[2024-11-22 15:36:41,892: INFO: 4198130749: Data loaded from data\raw]
[2024-11-22 15:36:41,907: INFO: 4198130749: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 15:36:41,915: ERROR: 4198130749: Error applying transformations: name 'data' is not defined]
[2024-11-22 15:37:13,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:37:13,455: INFO: common: created directory at: data\processed]
[2024-11-22 15:37:13,473: INFO: 1201523681: Data loaded from data\raw]
[2024-11-22 15:37:13,484: INFO: 1201523681: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 15:37:13,490: INFO: 1201523681: Applied transformations to data]
[2024-11-22 15:37:13,629: INFO: 1201523681: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 15:37:38,740: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:37:38,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:37:38,740: INFO: common: created directory at: data\raw]
[2024-11-22 15:37:41,511: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 15:37:41,511: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:37:41,511: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:37:41,527: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:37:41,527: INFO: common: created directory at: data\processed]
[2024-11-22 15:37:41,543: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 15:37:41,558: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 15:37:41,558: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 15:37:41,683: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 15:37:41,683: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 15:39:03,784: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 15:39:03,800: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:39:03,800: INFO: common: created directory at: data\raw]
[2024-11-22 15:39:06,133: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 15:39:06,148: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 15:39:06,148: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 15:39:06,148: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 15:39:06,148: INFO: common: created directory at: data\processed]
[2024-11-22 15:39:06,164: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 15:39:06,180: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 15:39:06,180: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 15:39:06,352: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 15:39:06,352: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 16:54:16,097: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 16:54:16,097: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 16:54:16,097: INFO: common: created directory at: data\raw]
[2024-11-22 16:54:17,941: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 16:54:17,941: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 16:54:17,941: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 16:54:17,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 16:54:17,957: INFO: common: created directory at: data\processed]
[2024-11-22 16:54:17,988: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 16:54:18,004: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 16:54:18,004: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 16:54:18,191: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 16:54:18,191: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 16:54:18,191: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 16:54:18,191: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 16:54:18,238: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 16:54:18,301: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 16:54:18,301: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 16:54:18,301: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 17:30:21,248: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 17:30:21,274: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 17:30:21,298: INFO: common: created directory at: data\raw]
[2024-11-22 17:30:24,911: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 17:30:24,917: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 17:30:24,917: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 17:30:24,928: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 17:30:24,932: INFO: common: created directory at: data\processed]
[2024-11-22 17:30:25,031: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 17:30:25,107: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 17:30:25,167: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 17:30:25,454: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 17:30:25,454: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 17:30:25,454: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 17:30:25,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 17:30:25,531: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 17:30:25,560: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 17:30:25,560: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 17:30:25,560: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 19:48:44,150: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 19:48:44,161: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 19:48:44,161: INFO: common: created directory at: data\raw]
[2024-11-22 19:48:46,087: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 19:48:46,094: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 19:48:46,094: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 19:48:46,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 19:48:46,096: INFO: common: created directory at: data\processed]
[2024-11-22 19:48:46,128: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 19:48:46,136: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 19:48:46,147: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 19:48:46,287: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 19:48:46,287: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 19:48:46,287: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 19:48:46,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 19:48:46,327: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 19:48:46,327: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 19:48:46,327: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 19:48:46,327: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 20:11:52,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 20:13:10,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 20:13:56,439: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 20:13:56,477: INFO: 694152386: Model built successfully.]
[2024-11-22 20:14:47,723: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 20:14:47,757: INFO: 2197671697: Model built successfully.]
[2024-11-22 21:25:10,068: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 21:25:10,087: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:25:10,090: INFO: common: created directory at: data\raw]
[2024-11-22 21:25:12,009: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 21:25:12,014: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 21:25:12,014: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 21:25:12,019: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:25:12,019: INFO: common: created directory at: data\processed]
[2024-11-22 21:25:12,049: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 21:25:12,062: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 21:25:12,069: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 21:25:12,201: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 21:25:12,202: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 21:25:12,202: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 21:25:12,207: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:25:12,242: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 21:25:12,246: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 21:25:12,247: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 21:25:12,247: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 21:25:12,248: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-22 21:25:12,251: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:25:12,277: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 21:25:12,279: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 21:25:12,280: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 21:25:12,280: INFO: main: >>> Stage Model Training Stage Completed<<<]
[2024-11-22 21:27:43,422: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 21:27:43,426: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:27:43,427: INFO: common: created directory at: data\raw]
[2024-11-22 21:27:45,340: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 21:27:45,345: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 21:27:45,346: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 21:27:45,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:27:45,351: INFO: common: created directory at: data\processed]
[2024-11-22 21:27:45,377: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 21:27:45,387: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 21:27:45,392: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 21:27:45,551: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 21:27:45,551: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 21:27:45,551: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 21:27:45,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:27:45,586: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 21:27:45,588: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 21:27:45,590: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 21:27:45,590: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 21:27:45,590: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-22 21:27:45,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:27:45,621: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 21:27:45,624: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 21:27:45,624: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 21:27:45,625: INFO: main: >>> Stage Model Training Stage Completed<<<]
[2024-11-22 21:28:39,157: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 21:28:39,162: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:28:39,162: INFO: common: created directory at: data\raw]
[2024-11-22 21:28:40,770: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 21:28:40,774: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 21:28:40,775: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 21:28:40,778: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:28:40,779: INFO: common: created directory at: data\processed]
[2024-11-22 21:28:40,801: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 21:28:40,810: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 21:28:40,815: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 21:28:40,951: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 21:28:40,951: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 21:28:40,952: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 21:28:40,958: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:28:40,990: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 21:28:40,993: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 21:28:40,994: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 21:28:40,994: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 21:28:40,994: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-22 21:28:40,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:28:40,998: ERROR: model_training: Error loading data: [Errno 2] No such file or directory: 'data\\processed\\stock_prices.csv']
[2024-11-22 21:31:57,935: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 21:31:57,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 21:31:57,946: INFO: common: created directory at: data\raw]
[2024-11-22 22:58:32,048: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 22:58:32,061: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:58:32,065: INFO: common: created directory at: data\raw]
[2024-11-22 22:58:34,559: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 22:58:34,563: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 22:58:34,563: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 22:58:34,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:58:34,570: INFO: common: created directory at: data\processed]
[2024-11-22 22:58:34,736: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 22:58:34,945: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 22:58:35,187: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 22:58:35,334: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 22:58:35,335: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 22:58:35,335: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 22:58:35,339: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:58:35,382: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 22:58:35,421: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 22:58:35,422: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 22:58:35,422: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 22:58:35,422: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-22 22:58:35,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:58:35,453: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-22 22:58:35,454: INFO: model_training: Data scaling complete.]
[2024-11-22 22:58:35,465: INFO: model_training: Data splitting complete.]
[2024-11-22 22:58:37,205: INFO: model_training: Model built successfully.]
[2024-11-22 22:58:59,099: INFO: model_training: Model training complete.]
[2024-11-22 22:59:01,310: INFO: model_training: Testing complete. RMSE: 0.7644726224334931]
[2024-11-22 22:59:39,340: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 22:59:39,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:59:39,340: INFO: common: created directory at: data\raw]
[2024-11-22 22:59:41,902: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 22:59:41,902: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 22:59:41,902: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 22:59:41,902: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:59:41,902: INFO: common: created directory at: data\processed]
[2024-11-22 22:59:41,917: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 22:59:41,933: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 22:59:41,933: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 22:59:42,074: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 22:59:42,074: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 22:59:42,074: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 22:59:42,074: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:59:42,121: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 22:59:42,121: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 22:59:42,121: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 22:59:42,121: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 22:59:42,121: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-22 22:59:42,121: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 22:59:42,152: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-22 22:59:42,152: INFO: model_training: Data scaling complete.]
[2024-11-22 22:59:42,166: INFO: model_training: Data splitting complete.]
[2024-11-22 22:59:42,200: INFO: model_training: Model built successfully.]
[2024-11-22 23:00:02,729: INFO: model_training: Model training complete.]
[2024-11-22 23:00:04,842: INFO: model_training: Testing complete. RMSE: 0.7092551413520698]
[2024-11-22 23:07:39,296: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 23:07:39,296: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:07:39,312: INFO: common: created directory at: data\raw]
[2024-11-22 23:07:41,389: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 23:07:41,389: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 23:07:41,389: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 23:07:41,389: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:07:41,404: INFO: common: created directory at: data\processed]
[2024-11-22 23:07:41,420: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 23:07:41,435: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 23:07:41,451: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 23:07:41,592: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 23:07:41,592: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 23:07:41,592: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 23:07:41,592: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:07:41,623: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 23:07:41,623: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 23:07:41,623: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 23:07:41,623: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 23:07:41,623: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-22 23:07:41,639: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:07:41,654: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-22 23:07:41,654: INFO: model_training: Data scaling complete.]
[2024-11-22 23:07:41,670: INFO: model_training: Data splitting complete.]
[2024-11-22 23:07:41,842: INFO: model_training: Model built successfully.]
[2024-11-22 23:08:04,230: INFO: model_training: Model training complete.]
[2024-11-22 23:08:06,833: INFO: model_training: Testing complete. RMSE: 0.8499694868484041]
[2024-11-22 23:08:06,833: INFO: stage04_model_training: Created directory: artifacts\model]
[2024-11-22 23:08:06,833: INFO: stage04_model_training: Directory already exists: artifacts\model]
[2024-11-22 23:08:07,005: INFO: model_training: Model saved to artifacts\model\trained_model.h5]
[2024-11-22 23:08:38,598: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-22 23:08:38,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:08:38,613: INFO: common: created directory at: data\raw]
[2024-11-22 23:08:40,316: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-22 23:08:40,316: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-22 23:08:40,316: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-22 23:08:40,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:08:40,316: INFO: common: created directory at: data\processed]
[2024-11-22 23:08:40,394: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-22 23:08:40,457: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-22 23:08:40,488: INFO: data_preprocessing: Applied transformations to data]
[2024-11-22 23:08:40,660: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-22 23:08:40,660: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-22 23:08:40,660: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-22 23:08:40,660: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:08:40,707: INFO: data_validate: Data loaded from data\processed]
[2024-11-22 23:08:40,707: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-22 23:08:40,707: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-22 23:08:40,707: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-22 23:08:40,707: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-22 23:08:40,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-22 23:08:40,738: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-22 23:08:40,738: INFO: model_training: Data scaling complete.]
[2024-11-22 23:08:40,753: INFO: model_training: Data splitting complete.]
[2024-11-22 23:08:40,878: INFO: model_training: Model built successfully.]
[2024-11-22 23:09:02,083: INFO: model_training: Model training complete.]
[2024-11-22 23:09:04,380: INFO: model_training: Testing complete. RMSE: 0.8732031548195305]
[2024-11-22 23:09:04,395: INFO: stage04_model_training: Directory already exists: artifacts\model]
[2024-11-22 23:09:04,395: INFO: stage04_model_training: Directory already exists: artifacts\model]
[2024-11-22 23:09:04,442: INFO: model_training: Model saved to artifacts\model\trained_model.h5]
[2024-11-22 23:09:04,458: INFO: stage04_model_training: Process complete. RMSE: 0.8732031548195305]
[2024-11-22 23:09:04,458: INFO: main: >>> Stage Model Training Stage Completed<<<]
[2024-11-25 15:12:29,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:13:36,884: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:14:10,292: ERROR: 2934497893: Error fetching real-time data: 'ModelEvaluationConfig' object has no attribute 'symbol']
[2024-11-25 15:20:16,833: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:21:19,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:25:55,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:26:46,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:27:42,970: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:28:29,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:30:06,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:30:12,646: INFO: 790234082: Real-time data fetched successfully.]
[2024-11-25 15:31:51,303: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:31:53,691: INFO: 2934497893: Real-time data fetched successfully.]
[2024-11-25 15:38:09,598: INFO: 2136414290: Fetching and preprocessing real-time data...]
[2024-11-25 15:38:11,202: INFO: 2934497893: Real-time data fetched successfully.]
[2024-11-25 15:38:11,202: INFO: 2934497893: Real-time data fetched for symbol: IBM]
[2024-11-25 15:38:11,229: INFO: 2934497893: Real-time data scaled.]
[2024-11-25 15:39:21,059: INFO: 2934497893: Real-time data fetched successfully.]
[2024-11-25 15:39:21,059: INFO: 2934497893: Real-time data fetched for symbol: IBM]
[2024-11-25 15:39:21,075: INFO: 2934497893: Real-time data scaled.]
[2024-11-25 15:40:52,209: INFO: 3867280440: Testing model on real-time data...]
[2024-11-25 15:41:34,064: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:41:37,587: INFO: 3867280440: Testing model on real-time data...]
[2024-11-25 15:41:44,325: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 15:41:44,325: ERROR: 949639099: Error during real-time model testing: _create_sequences() takes 2 positional arguments but 3 were given]
[2024-11-25 15:41:54,822: INFO: 949639099: Real-time data fetched successfully.]
[2024-11-25 15:41:54,824: INFO: 949639099: Real-time data fetched for symbol: IBM]
[2024-11-25 15:41:54,834: INFO: 949639099: Real-time data scaled.]
[2024-11-25 15:41:55,294: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 15:41:55,297: ERROR: 949639099: Error during real-time model testing: _create_sequences() takes 2 positional arguments but 3 were given]
[2024-11-25 15:43:32,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:43:35,260: INFO: 2051497121: Real-time data fetched successfully.]
[2024-11-25 15:43:36,996: INFO: 2051497121: Real-time data fetched successfully.]
[2024-11-25 15:43:37,001: INFO: 2051497121: Real-time data fetched for symbol: IBM]
[2024-11-25 15:43:37,006: INFO: 2051497121: Real-time data scaled.]
[2024-11-25 15:43:37,706: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 15:43:37,711: ERROR: 2051497121: Error during real-time model testing: _create_sequences() takes 2 positional arguments but 3 were given]
[2024-11-25 15:55:54,452: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:55:57,171: INFO: 2066236155: Real-time data fetched successfully.]
[2024-11-25 15:55:59,558: INFO: 2066236155: Real-time data fetched successfully.]
[2024-11-25 15:55:59,563: INFO: 2066236155: Real-time data fetched for symbol: IBM]
[2024-11-25 15:55:59,569: INFO: 2066236155: Real-time data scaled.]
[2024-11-25 15:56:01,012: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 15:56:01,013: ERROR: 2066236155: Error during real-time model testing: name 'sequence_length' is not defined]
[2024-11-25 15:57:02,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:57:07,196: INFO: 1450174731: Real-time data fetched successfully.]
[2024-11-25 15:57:08,527: INFO: 1450174731: Real-time data fetched successfully.]
[2024-11-25 15:57:08,531: INFO: 1450174731: Real-time data fetched for symbol: IBM]
[2024-11-25 15:57:08,531: INFO: 1450174731: Real-time data scaled.]
[2024-11-25 15:57:17,785: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 15:57:17,797: ERROR: 1450174731: Error during real-time model testing: No file or directory found at artifacts\model.h5]
[2024-11-25 15:58:07,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:58:09,133: INFO: 1450174731: Real-time data fetched successfully.]
[2024-11-25 15:58:10,807: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 15:58:12,904: INFO: 1450174731: Real-time data fetched successfully.]
[2024-11-25 15:58:14,053: INFO: 1450174731: Real-time data fetched successfully.]
[2024-11-25 15:58:14,054: INFO: 1450174731: Real-time data fetched for symbol: IBM]
[2024-11-25 15:58:14,056: INFO: 1450174731: Real-time data scaled.]
[2024-11-25 15:58:14,089: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 15:58:15,701: INFO: 1450174731: Real-time model testing complete.]
[2024-11-25 16:02:34,442: INFO: 1450174731: Real-time data fetched successfully.]
[2024-11-25 16:19:01,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 16:19:04,608: INFO: 2139741253: Real-time data fetched successfully.]
[2024-11-25 16:19:07,238: INFO: 2139741253: Real-time data fetched successfully.]
[2024-11-25 16:19:07,238: INFO: 2139741253: Real-time data fetched for symbol: IBM]
[2024-11-25 16:19:07,248: INFO: 2139741253: Real-time data scaled.]
[2024-11-25 16:19:43,474: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 16:19:44,585: INFO: 2139741253: Real-time model testing complete.]
[2024-11-25 16:20:03,023: ERROR: 2139741253: Error during model testing: _create_sequences() got an unexpected keyword argument 'sequence_length']
[2024-11-25 16:20:38,797: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 16:20:42,165: INFO: 3066542885: Real-time data fetched successfully.]
[2024-11-25 16:20:43,534: INFO: 3066542885: Real-time data fetched successfully.]
[2024-11-25 16:20:43,537: INFO: 3066542885: Real-time data fetched for symbol: IBM]
[2024-11-25 16:20:43,543: INFO: 3066542885: Real-time data scaled.]
[2024-11-25 16:20:48,777: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 16:20:49,864: INFO: 3066542885: Real-time model testing complete.]
[2024-11-25 16:20:51,755: ERROR: 3066542885: Error during model testing: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.]
[2024-11-25 16:30:56,063: INFO: 3066542885: Real-time data fetched successfully.]
[2024-11-25 16:31:45,435: INFO: 3066542885: Real-time data fetched successfully.]
[2024-11-25 16:31:45,435: INFO: 3066542885: Real-time data fetched for symbol: IBM]
[2024-11-25 16:31:45,470: INFO: 3066542885: Real-time data scaled.]
[2024-11-25 21:25:41,898: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-25 21:25:41,911: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:25:41,915: INFO: common: created directory at: data\raw]
[2024-11-25 21:25:44,458: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-25 21:25:44,468: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-25 21:25:44,468: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-25 21:25:44,473: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:25:44,473: INFO: common: created directory at: data\processed]
[2024-11-25 21:25:44,497: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-25 21:25:44,517: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-25 21:25:44,521: INFO: data_preprocessing: Applied transformations to data]
[2024-11-25 21:25:44,662: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-25 21:25:44,662: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-25 21:25:44,662: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-25 21:25:44,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:25:44,698: INFO: data_validate: Data loaded from data\processed]
[2024-11-25 21:25:44,698: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-25 21:25:44,698: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-25 21:25:44,698: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-25 21:25:44,698: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-25 21:25:44,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:25:44,731: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-25 21:25:44,736: ERROR: model_training: Error during data scaling: 'ModelTrainingConfig' object has no attribute 'scaler_path']
[2024-11-25 21:27:29,822: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-25 21:27:29,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:27:29,836: INFO: common: created directory at: data\raw]
[2024-11-25 21:27:31,278: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-25 21:27:31,278: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-25 21:27:31,278: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-25 21:27:31,287: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:27:31,287: INFO: common: created directory at: data\processed]
[2024-11-25 21:27:31,318: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-25 21:27:31,332: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-25 21:27:31,338: INFO: data_preprocessing: Applied transformations to data]
[2024-11-25 21:27:31,489: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-25 21:27:31,489: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-25 21:27:31,489: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-25 21:27:31,498: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:27:31,528: INFO: data_validate: Data loaded from data\processed]
[2024-11-25 21:27:31,528: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-25 21:27:31,533: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-25 21:27:31,533: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-25 21:27:31,533: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-25 21:27:31,538: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:27:31,558: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-25 21:27:31,558: ERROR: model_training: Error during data scaling: [Errno 2] No such file or directory: 'artifacts\\scaler\\scaler.pkl']
[2024-11-25 21:30:57,307: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-25 21:30:57,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:30:57,317: INFO: common: created directory at: data\raw]
[2024-11-25 21:30:58,819: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-25 21:30:58,825: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-25 21:30:58,825: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-25 21:30:58,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:30:58,828: INFO: common: created directory at: data\processed]
[2024-11-25 21:30:58,857: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-25 21:30:58,869: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-25 21:30:58,882: INFO: data_preprocessing: Applied transformations to data]
[2024-11-25 21:30:59,018: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-25 21:30:59,018: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-25 21:30:59,018: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-25 21:30:59,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:30:59,058: INFO: data_validate: Data loaded from data\processed]
[2024-11-25 21:30:59,058: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-25 21:30:59,058: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-25 21:30:59,058: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-25 21:30:59,058: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-25 21:30:59,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:30:59,089: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-25 21:30:59,097: INFO: model_training: Scaler saved to artifacts\scaler\scaler.pkl]
[2024-11-25 21:30:59,097: INFO: model_training: Data scaling complete.]
[2024-11-25 21:30:59,108: INFO: model_training: Data splitting complete.]
[2024-11-25 21:30:59,231: INFO: model_training: Model built successfully.]
[2024-11-25 21:31:24,749: INFO: model_training: Model training complete.]
[2024-11-25 21:31:24,808: ERROR: model_training: Error during model testing: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.]
[2024-11-25 21:33:23,687: INFO: 3066542885: Real-time data fetched successfully.]
[2024-11-25 21:33:23,691: INFO: 3066542885: Real-time data fetched for symbol: IBM]
[2024-11-25 21:33:23,698: INFO: 3066542885: Real-time data scaled.]
[2024-11-25 21:33:26,472: WARNING: polymorphic_function: 5 out of the last 9 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000260184BCDC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-11-25 21:47:39,315: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:47:44,900: INFO: 200222525: Real-time data fetched successfully.]
[2024-11-25 21:47:52,500: INFO: 200222525: Real-time data fetched successfully.]
[2024-11-25 21:47:52,502: INFO: 200222525: Real-time data fetched for symbol: IBM]
[2024-11-25 21:47:52,518: INFO: 200222525: Real-time data scaled.]
[2024-11-25 21:47:53,948: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 21:47:55,254: WARNING: polymorphic_function: 6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000260186FF5E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-11-25 21:47:55,272: INFO: 200222525: Real-time model testing complete.]
[2024-11-25 21:47:57,883: ERROR: 200222525: Error during model testing: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.]
[2024-11-25 21:57:20,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 21:57:28,548: INFO: 3407295656: Real-time data fetched successfully.]
[2024-11-25 21:57:34,977: INFO: 3407295656: Real-time data fetched successfully.]
[2024-11-25 21:57:34,977: INFO: 3407295656: Real-time data fetched for symbol: IBM]
[2024-11-25 21:57:34,990: INFO: 3407295656: Real-time data scaled.]
[2024-11-25 21:57:35,025: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 21:57:36,430: INFO: 3407295656: Real-time model testing complete.]
[2024-11-25 21:57:37,153: ERROR: 3407295656: Error during model testing: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.]
[2024-11-25 22:02:06,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:02:08,277: INFO: 2610756440: Real-time data fetched successfully.]
[2024-11-25 22:02:14,760: INFO: 2610756440: Real-time data fetched successfully.]
[2024-11-25 22:02:14,768: INFO: 2610756440: Real-time data fetched for symbol: IBM]
[2024-11-25 22:02:14,776: INFO: 2610756440: Real-time data scaled.]
[2024-11-25 22:02:18,047: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:02:20,109: INFO: 2610756440: Real-time model testing complete.]
[2024-11-25 22:02:27,170: ERROR: 2610756440: Error during model testing: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.]
[2024-11-25 22:04:24,879: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:04:26,597: INFO: 1863302823: Real-time data fetched successfully.]
[2024-11-25 22:04:30,413: INFO: 1863302823: Real-time data fetched successfully.]
[2024-11-25 22:04:30,419: INFO: 1863302823: Real-time data fetched for symbol: IBM]
[2024-11-25 22:04:30,419: INFO: 1863302823: Real-time data scaled.]
[2024-11-25 22:04:31,168: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:04:33,172: INFO: 1863302823: Real-time model testing complete.]
[2024-11-25 22:04:36,106: ERROR: 1863302823: Error during model testing: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.]
[2024-11-25 22:09:15,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:09:17,199: INFO: 4065861878: Real-time data fetched successfully.]
[2024-11-25 22:09:19,172: INFO: 4065861878: Real-time data fetched successfully.]
[2024-11-25 22:09:19,180: INFO: 4065861878: Real-time data fetched for symbol: IBM]
[2024-11-25 22:09:19,187: INFO: 4065861878: Real-time data scaled.]
[2024-11-25 22:09:20,648: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:09:22,498: INFO: 4065861878: Real-time model testing complete.]
[2024-11-25 22:09:28,682: ERROR: 4065861878: Error during model testing: name 'test_data' is not defined]
[2024-11-25 22:09:54,634: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:09:55,717: INFO: 1294665694: Real-time data fetched successfully.]
[2024-11-25 22:09:57,362: INFO: 1294665694: Real-time data fetched successfully.]
[2024-11-25 22:09:57,367: INFO: 1294665694: Real-time data fetched for symbol: IBM]
[2024-11-25 22:09:57,370: INFO: 1294665694: Real-time data scaled.]
[2024-11-25 22:09:58,429: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:10:00,962: INFO: 1294665694: Real-time model testing complete.]
[2024-11-25 22:10:05,162: ERROR: 1294665694: Error during model testing: operands could not be broadcast together with shapes (40,1) (0,1) ]
[2024-11-25 22:31:09,637: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:31:11,050: INFO: 3876630375: Real-time data fetched successfully.]
[2024-11-25 22:31:11,862: INFO: 3876630375: Real-time data fetched successfully.]
[2024-11-25 22:31:11,863: INFO: 3876630375: Real-time data fetched for symbol: IBM]
[2024-11-25 22:31:11,894: INFO: 3876630375: Real-time data scaled.]
[2024-11-25 22:31:12,183: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:31:14,798: INFO: 3876630375: Real-time model testing complete.]
[2024-11-25 22:31:26,472: ERROR: 3876630375: Error during model testing: operands could not be broadcast together with shapes (40,1) (100,1) ]
[2024-11-25 22:38:40,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:38:41,996: INFO: 1928877316: Real-time data fetched successfully.]
[2024-11-25 22:38:44,002: INFO: 1928877316: Real-time data fetched successfully.]
[2024-11-25 22:38:44,006: INFO: 1928877316: Real-time data fetched for symbol: IBM]
[2024-11-25 22:38:44,006: INFO: 1928877316: Real-time data scaled.]
[2024-11-25 22:38:45,303: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:38:47,291: INFO: 1928877316: Real-time model testing complete.]
[2024-11-25 22:38:58,732: INFO: 1928877316: Testing complete. RMSE: 222.69284527367168]
[2024-11-25 22:40:08,701: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:40:10,115: INFO: 1069016221: Real-time data fetched successfully.]
[2024-11-25 22:40:12,095: INFO: 1069016221: Real-time data fetched successfully.]
[2024-11-25 22:40:12,095: INFO: 1069016221: Real-time data fetched for symbol: IBM]
[2024-11-25 22:40:12,103: INFO: 1069016221: Real-time data scaled.]
[2024-11-25 22:40:12,145: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:40:14,354: INFO: 1069016221: Real-time model testing complete.]
[2024-11-25 22:40:16,507: ERROR: 1069016221: Error during model testing: Expected 2D array, got 1D array instead:
array=[0.47297297 0.33783784 0.47297297 0.40540541 0.40540541 0.47297297
 0.92567568 0.65540541 0.67567568 0.49324324 0.5        0.47297297
 0.47972973 0.31756757 0.47297297 0.50675676 0.47972973 0.54054054
 0.31756757 0.47972973 0.50777027 0.54054054 0.51351351 0.50675676
 0.47972973 0.47972973 0.47972973 0.43918919 0.54054054 0.40540541
 0.55398649 0.54054054 0.54054054 0.54054054 0.54054054 0.43918919
 0.54054054 0.54054054 0.54054054 0.55405405].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.]
[2024-11-25 22:45:43,512: INFO: 1069016221: Real-time data fetched successfully.]
[2024-11-25 22:45:43,513: INFO: 1069016221: Real-time data fetched for symbol: IBM]
[2024-11-25 22:45:43,513: INFO: 1069016221: Real-time data scaled.]
[2024-11-25 22:47:26,933: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:47:28,292: INFO: 1188819448: Real-time data fetched successfully.]
[2024-11-25 22:47:29,932: INFO: 1188819448: Real-time data fetched successfully.]
[2024-11-25 22:47:29,932: INFO: 1188819448: Real-time data fetched for symbol: IBM]
[2024-11-25 22:47:29,937: INFO: 1188819448: Real-time data scaled.]
[2024-11-25 22:47:30,811: INFO: 1618695276: Testing model on real-time data...]
[2024-11-25 22:47:32,731: INFO: 1188819448: Real-time model testing complete.]
[2024-11-25 22:47:37,441: INFO: 1188819448: Testing complete. RMSE: 0.17130185216641108]
[2024-11-25 22:50:42,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 22:50:44,504: INFO: 2868438523: Real-time data fetched successfully.]
[2024-11-25 22:50:44,991: ERROR: 2868438523: Error fetching real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 22:50:44,994: ERROR: 2868438523: Error fetching and preprocessing real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 22:51:00,149: ERROR: 2868438523: Error fetching real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 22:51:00,152: ERROR: 2868438523: Error fetching and preprocessing real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:02:00,812: ERROR: 2868438523: Error fetching real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:02:00,812: ERROR: 2868438523: Error fetching and preprocessing real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:17:35,705: ERROR: 2868438523: Error fetching real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:17:35,707: ERROR: 2868438523: Error fetching and preprocessing real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:22:18,660: ERROR: 2868438523: Error fetching real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:22:18,660: ERROR: 2868438523: Error fetching and preprocessing real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:22:31,255: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 23:22:32,380: ERROR: 2868438523: Error fetching real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-25 23:23:35,793: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-25 23:23:39,091: ERROR: 2868438523: Error fetching real-time data: Unexpected response format: {'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}]
[2024-11-26 13:36:09,481: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:36:14,616: INFO: 2868438523: Real-time data fetched successfully.]
[2024-11-26 13:36:18,796: INFO: 2868438523: Real-time data fetched successfully.]
[2024-11-26 13:36:18,796: INFO: 2868438523: Real-time data fetched for symbol: IBM]
[2024-11-26 13:36:18,809: INFO: 2868438523: Real-time data scaled.]
[2024-11-26 13:36:26,536: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 13:36:30,106: INFO: 2868438523: Real-time model testing complete.]
[2024-11-26 13:36:45,208: INFO: 2868438523: Testing complete. RMSE: 0.32317496113223915]
[2024-11-26 13:37:34,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:37:36,740: INFO: 1108937008: Real-time data fetched successfully.]
[2024-11-26 13:37:44,360: ERROR: 1108937008: Error fetching real-time data: HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=1min&apikey=5MS2QHOO22O2TYGA&datatype=json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1149)')))]
[2024-11-26 13:37:44,362: ERROR: 1108937008: Error fetching and preprocessing real-time data: HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=1min&apikey=5MS2QHOO22O2TYGA&datatype=json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1149)')))]
[2024-11-26 13:38:03,027: INFO: 1108937008: Real-time data fetched successfully.]
[2024-11-26 13:38:03,032: INFO: 1108937008: Real-time data fetched for symbol: IBM]
[2024-11-26 13:38:03,037: INFO: 1108937008: Real-time data scaled.]
[2024-11-26 13:38:11,171: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 13:38:13,741: INFO: 1108937008: Real-time model testing complete.]
[2024-11-26 13:38:19,741: INFO: 1108937008: Testing complete. RMSE: 0.32317496113223915]
[2024-11-26 13:39:11,497: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-26 13:39:11,512: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:39:11,512: INFO: common: created directory at: data\raw]
[2024-11-26 13:39:14,299: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-26 13:39:14,302: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-26 13:39:14,302: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-26 13:39:14,311: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:39:14,312: INFO: common: created directory at: data\processed]
[2024-11-26 13:39:14,343: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-26 13:39:14,358: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-26 13:39:14,373: INFO: data_preprocessing: Applied transformations to data]
[2024-11-26 13:39:14,592: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-26 13:39:14,592: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-26 13:39:14,592: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-26 13:39:14,592: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:39:14,639: INFO: data_validate: Data loaded from data\processed]
[2024-11-26 13:39:14,639: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-26 13:39:14,639: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-26 13:39:14,639: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-26 13:39:14,639: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-26 13:39:14,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:39:14,686: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-26 13:39:14,686: INFO: model_training: Scaler saved to artifacts\scaler\scaler.pkl]
[2024-11-26 13:39:14,686: INFO: model_training: Data scaling complete.]
[2024-11-26 13:39:14,701: INFO: model_training: Data splitting complete.]
[2024-11-26 13:39:14,779: INFO: model_training: Model built successfully.]
[2024-11-26 13:39:48,021: INFO: model_training: Model training complete.]
[2024-11-26 13:39:48,099: ERROR: model_training: Error during model testing: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.]
[2024-11-26 13:42:03,203: INFO: main: >>> Stage Data Ingestion Stage Started<<<]
[2024-11-26 13:42:03,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:42:03,219: INFO: common: created directory at: data\raw]
[2024-11-26 13:42:05,562: INFO: data_ingestion: Raw data saved to data\raw\IBM_stock_data.csv]
[2024-11-26 13:42:05,577: INFO: main: >>> Stage Data Ingestion Stage Completed<<<]
[2024-11-26 13:42:05,577: INFO: main: >>> Stage Data Preprocessing Stage Started<<<]
[2024-11-26 13:42:05,577: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:42:05,577: INFO: common: created directory at: data\processed]
[2024-11-26 13:42:05,637: INFO: data_preprocessing: Data loaded from data\raw]
[2024-11-26 13:42:05,655: INFO: data_preprocessing: Renamed 'Unnamed: 0' to 'date' and set as index]
[2024-11-26 13:42:05,667: INFO: data_preprocessing: Applied transformations to data]
[2024-11-26 13:42:05,844: INFO: data_preprocessing: Processed data saved to data\processed\processed_stock_data.csv]
[2024-11-26 13:42:05,844: INFO: main: >>> Stage Data Preprocessing Stage Completed<<<]
[2024-11-26 13:42:05,844: INFO: main: >>> Stage Data validation Stage Started<<<]
[2024-11-26 13:42:05,844: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:42:05,891: INFO: data_validate: Data loaded from data\processed]
[2024-11-26 13:42:05,891: INFO: data_validate: Validation passed. Data is correctly formatted.]
[2024-11-26 13:42:05,891: INFO: data_validate: Data validation pipeline completed successfully.]
[2024-11-26 13:42:05,891: INFO: main: >>> Stage Data validation Stage Completed<<<]
[2024-11-26 13:42:05,891: INFO: main: >>> Stage Model Training Stage Started<<<]
[2024-11-26 13:42:05,907: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 13:42:05,938: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-26 13:42:05,938: INFO: model_training: Scaler saved to artifacts\scaler\scaler.pkl]
[2024-11-26 13:42:05,938: INFO: model_training: Data scaling complete.]
[2024-11-26 13:42:05,969: INFO: model_training: Data splitting complete.]
[2024-11-26 13:42:06,032: INFO: model_training: Model built successfully.]
[2024-11-26 13:42:42,202: INFO: model_training: Model training complete.]
[2024-11-26 13:42:42,202: INFO: stage04_model_training: Directory already exists: artifacts\model]
[2024-11-26 13:42:42,249: INFO: model_training: Model saved to artifacts\model\trained_model.h5]
[2024-11-26 13:42:42,265: INFO: main: >>> Stage Model Training Stage Completed<<<]
[2024-11-26 14:03:40,415: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:03:42,804: ERROR: 3386568819: Error logging to MLflow: name 'rmse' is not defined]
[2024-11-26 14:07:30,454: WARNING: polymorphic_function: 5 out of the last 9 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000280F509C310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-11-26 14:07:30,554: INFO: 1108937008: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 14:07:32,616: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:07:35,988: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77A9FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:07:42,035: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F55F7370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:07:52,093: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77A9970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:08:10,123: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77A9B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:08:44,185: WARNING: connectionpool: Retrying (JitteredRetry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77A9550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:08:46,245: ERROR: 1108937008: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77A97C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:08:46,249: ERROR: 3386568819: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77A97C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:10:32,623: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:10:35,431: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F33DAF70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:10:41,477: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F670BFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:10:51,523: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F772F310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:11:09,568: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F772F640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:11:43,606: WARNING: connectionpool: Retrying (JitteredRetry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F7774D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction]
[2024-11-26 14:11:45,636: ERROR: 1108937008: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F7774B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:11:45,636: ERROR: 3386568819: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stock+Price+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F7774B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:14:31,712: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 14:23:27,388: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 14:23:30,622: INFO: 1583435681: Real-time data fetched successfully.]
[2024-11-26 14:23:33,315: INFO: 1583435681: Real-time data fetched successfully.]
[2024-11-26 14:23:33,317: INFO: 1583435681: Real-time data fetched for symbol: IBM]
[2024-11-26 14:23:33,407: INFO: 1583435681: Real-time data scaled.]
[2024-11-26 14:23:33,976: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 14:23:36,474: WARNING: polymorphic_function: 6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000280F4E41D30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-11-26 14:23:36,506: INFO: 1583435681: Real-time model testing complete.]
[2024-11-26 14:23:39,729: INFO: 1583435681: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 14:23:41,174: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:23:42,005: ERROR: 1583435681: Error logging to MLflow: name 'urlparse' is not defined]
[2024-11-26 14:23:42,005: ERROR: 3386568819: Error logging to MLflow: name 'urlparse' is not defined]
[2024-11-26 14:25:19,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 14:25:22,283: INFO: 747207056: Real-time data fetched successfully.]
[2024-11-26 14:25:24,923: INFO: 747207056: Real-time data fetched successfully.]
[2024-11-26 14:25:24,923: INFO: 747207056: Real-time data fetched for symbol: IBM]
[2024-11-26 14:25:24,934: INFO: 747207056: Real-time data scaled.]
[2024-11-26 14:25:25,003: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 14:25:29,465: INFO: 747207056: Real-time model testing complete.]
[2024-11-26 14:25:32,918: INFO: 747207056: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 14:25:33,965: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:25:37,050: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F8A04160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:25:43,108: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F8A04520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:25:53,142: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F792B2E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:26:11,211: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F792B3D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:26:45,256: WARNING: connectionpool: Retrying (JitteredRetry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F792BFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:26:47,313: ERROR: 747207056: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F792BD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:26:47,313: ERROR: 3386568819: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F792BD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:40:38,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 14:40:40,993: INFO: 747207056: Real-time data fetched successfully.]
[2024-11-26 14:40:42,838: INFO: 747207056: Real-time data fetched successfully.]
[2024-11-26 14:40:42,843: INFO: 747207056: Real-time data fetched for symbol: IBM]
[2024-11-26 14:40:44,529: INFO: 747207056: Real-time data scaled.]
[2024-11-26 14:40:46,020: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 14:40:48,865: INFO: 747207056: Real-time model testing complete.]
[2024-11-26 14:40:54,027: INFO: 747207056: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 14:40:55,057: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:40:57,676: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F342B5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:41:03,711: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F3581460>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:41:13,751: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F5321C40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:41:31,787: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F4EBA700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:42:05,812: WARNING: connectionpool: Retrying (JitteredRetry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F34626A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:42:07,834: ERROR: 747207056: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77F9910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:42:07,836: ERROR: 3386568819: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F77F9910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:48:27,893: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:48:30,889: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FB5BC370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:48:36,923: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F9B53C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:48:46,956: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FB74F220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:49:05,007: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F350F850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:49:39,028: WARNING: connectionpool: Retrying (JitteredRetry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280F350FDF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:49:41,046: ERROR: 747207056: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FB724580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:49:41,046: ERROR: 3386568819: Error logging to MLflow: API request to http://127.0.0.1:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FB724580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))]
[2024-11-26 14:49:49,321: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 14:49:51,363: INFO: 747207056: Real-time data fetched successfully.]
[2024-11-26 14:49:52,404: INFO: 747207056: Real-time data fetched successfully.]
[2024-11-26 14:49:52,404: INFO: 747207056: Real-time data fetched for symbol: IBM]
[2024-11-26 14:49:52,404: INFO: 747207056: Real-time data scaled.]
[2024-11-26 14:49:52,634: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 14:49:54,077: INFO: 747207056: Real-time model testing complete.]
[2024-11-26 14:49:56,935: INFO: 747207056: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 14:50:00,714: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 14:50:04,666: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FCA28880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:50:10,745: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FCA289A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:50:20,779: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FCA28730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create]
[2024-11-26 14:58:32,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 14:58:34,865: INFO: 3236723945: Real-time data fetched successfully.]
[2024-11-26 14:58:37,350: INFO: 3236723945: Real-time data fetched successfully.]
[2024-11-26 14:58:37,350: INFO: 3236723945: Real-time data fetched for symbol: IBM]
[2024-11-26 14:58:37,357: INFO: 3236723945: Real-time data scaled.]
[2024-11-26 14:58:38,177: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 14:58:39,838: INFO: 3236723945: Real-time model testing complete.]
[2024-11-26 14:58:43,011: INFO: 3236723945: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 14:59:14,929: INFO: builder_impl: Assets written to: C:\Users\Portable\AppData\Local\Temp\tmpni5bcocd\model\data\model\assets]
[2024-11-26 18:24:10,264: INFO: builder_impl: Assets written to: C:\Users\Portable\AppData\Local\Temp\tmp2zhfharf\model\data\model\assets]
[2024-11-26 18:33:34,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:33:42,619: ERROR: 1115350102: Error fetching real-time data: HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=1min&apikey=5MS2QHOO22O2TYGA&datatype=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4FB0B6430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))]
[2024-11-26 18:34:52,329: INFO: 1115350102: Real-time data fetched successfully.]
[2024-11-26 18:35:05,373: INFO: 1115350102: Real-time data fetched successfully.]
[2024-11-26 18:35:05,373: INFO: 1115350102: Real-time data fetched for symbol: IBM]
[2024-11-26 18:35:05,389: INFO: 1115350102: Real-time data scaled.]
[2024-11-26 18:35:07,096: INFO: 1618695276: Testing model on real-time data...]
[2024-11-26 18:35:09,986: INFO: 1115350102: Real-time model testing complete.]
[2024-11-26 18:35:15,198: INFO: 1115350102: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 18:35:31,381: INFO: 3386568819: Logging results to MLflow...]
[2024-11-26 18:35:42,591: INFO: builder_impl: Assets written to: C:\Users\Portable\AppData\Local\Temp\tmpllu2k1_w\model\data\model\assets]
[2024-11-26 18:43:57,792: INFO: main: >>> Stage Model Evaluation Stage Started<<<]
[2024-11-26 18:43:57,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:43:57,865: INFO: model_training: Data loaded from data\processed\processed_stock_data.csv]
[2024-11-26 18:43:57,881: INFO: model_training: Scaler saved to artifacts\scaler\scaler.pkl]
[2024-11-26 18:43:57,881: INFO: model_training: Data scaling complete.]
[2024-11-26 18:43:57,914: INFO: model_training: Data splitting complete.]
[2024-11-26 18:43:58,098: INFO: model_training: Model built successfully.]
[2024-11-26 18:44:31,288: INFO: main: >>> Stage Model Evaluation Stage Started<<<]
[2024-11-26 18:44:31,288: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:44:33,820: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:44:33,820: INFO: stage05_model_evaluation: Testing model on real-time data...]
[2024-11-26 18:45:25,155: INFO: main: >>> Stage Model Evaluation Stage Started<<<]
[2024-11-26 18:45:25,155: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:45:26,702: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:45:27,609: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:45:27,609: INFO: model_evaluation_mlflow: Real-time data fetched for symbol: IBM]
[2024-11-26 18:45:27,609: INFO: model_evaluation_mlflow: Real-time data scaled.]
[2024-11-26 18:45:27,609: INFO: stage05_model_evaluation: Testing model on real-time data...]
[2024-11-26 18:45:29,437: INFO: model_evaluation_mlflow: Real-time model testing complete.]
[2024-11-26 18:45:30,874: INFO: model_evaluation_mlflow: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 18:45:30,874: INFO: stage05_model_evaluation: Logging results to MLflow...]
[2024-11-26 18:45:30,874: ERROR: stage05_model_evaluation: Error logging to MLflow: name 'load_model' is not defined]
[2024-11-26 18:45:30,874: INFO: main: >>> Stage Model Evaluation Stage Completed<<<]
[2024-11-26 18:46:05,285: INFO: main: >>> Stage Model Evaluation Stage Started<<<]
[2024-11-26 18:46:05,291: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:46:06,078: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:46:06,671: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:46:06,671: INFO: model_evaluation_mlflow: Real-time data fetched for symbol: IBM]
[2024-11-26 18:46:06,671: INFO: model_evaluation_mlflow: Real-time data scaled.]
[2024-11-26 18:46:06,671: INFO: stage05_model_evaluation: Testing model on real-time data...]
[2024-11-26 18:46:08,389: INFO: model_evaluation_mlflow: Real-time model testing complete.]
[2024-11-26 18:46:09,763: INFO: model_evaluation_mlflow: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 18:46:09,763: INFO: stage05_model_evaluation: Logging results to MLflow...]
[2024-11-26 18:46:09,763: ERROR: stage05_model_evaluation: Error logging to MLflow: log_to_mlflow() missing 1 required positional argument: 'model']
[2024-11-26 18:46:09,763: INFO: main: >>> Stage Model Evaluation Stage Completed<<<]
[2024-11-26 18:48:00,273: INFO: main: >>> Stage Model Evaluation Stage Started<<<]
[2024-11-26 18:48:00,289: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:48:01,257: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:48:01,867: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:48:01,867: INFO: model_evaluation_mlflow: Real-time data fetched for symbol: IBM]
[2024-11-26 18:48:01,883: INFO: model_evaluation_mlflow: Real-time data scaled.]
[2024-11-26 18:48:01,883: INFO: stage05_model_evaluation: Testing model on real-time data...]
[2024-11-26 18:48:03,570: INFO: model_evaluation_mlflow: Real-time model testing complete.]
[2024-11-26 18:48:04,929: INFO: model_evaluation_mlflow: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 18:48:04,929: INFO: stage05_model_evaluation: Logging results to MLflow...]
[2024-11-26 18:48:05,508: ERROR: model_evaluation_mlflow: Error logging to MLflow: name 'urlparse' is not defined]
[2024-11-26 18:48:05,508: ERROR: stage05_model_evaluation: Error logging to MLflow: name 'urlparse' is not defined]
[2024-11-26 18:48:05,508: INFO: main: >>> Stage Model Evaluation Stage Completed<<<]
[2024-11-26 18:48:49,488: INFO: main: >>> Stage Model Evaluation Stage Started<<<]
[2024-11-26 18:48:49,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:48:50,831: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:48:52,036: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:48:52,051: INFO: model_evaluation_mlflow: Real-time data fetched for symbol: IBM]
[2024-11-26 18:48:52,051: INFO: model_evaluation_mlflow: Real-time data scaled.]
[2024-11-26 18:48:52,051: INFO: stage05_model_evaluation: Testing model on real-time data...]
[2024-11-26 18:48:53,722: INFO: model_evaluation_mlflow: Real-time model testing complete.]
[2024-11-26 18:48:55,158: INFO: model_evaluation_mlflow: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 18:48:55,158: INFO: stage05_model_evaluation: Logging results to MLflow...]
[2024-11-26 18:49:18,648: WARNING: connectionpool: Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A74B6B7A60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /BouazizOmar/Automated-Stock-Price-Prediction-Pipeline-A-Complete-MLOps-Lifecycle.mlflow/api/2.0/mlflow/runs/create]
[2024-11-26 18:49:22,651: WARNING: connectionpool: Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A74B6B71F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /BouazizOmar/Automated-Stock-Price-Prediction-Pipeline-A-Complete-MLOps-Lifecycle.mlflow/api/2.0/mlflow/runs/create]
[2024-11-26 18:49:30,654: WARNING: connectionpool: Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A74B6B79A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /BouazizOmar/Automated-Stock-Price-Prediction-Pipeline-A-Complete-MLOps-Lifecycle.mlflow/api/2.0/mlflow/runs/create]
[2024-11-26 18:49:46,656: WARNING: connectionpool: Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A74B6B7880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /BouazizOmar/Automated-Stock-Price-Prediction-Pipeline-A-Complete-MLOps-Lifecycle.mlflow/api/2.0/mlflow/runs/create]
[2024-11-26 18:56:26,022: INFO: main: >>> Stage Model Evaluation Stage Started<<<]
[2024-11-26 18:56:26,038: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-26 18:56:26,898: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:56:27,632: INFO: model_evaluation_mlflow: Real-time data fetched successfully.]
[2024-11-26 18:56:27,632: INFO: model_evaluation_mlflow: Real-time data fetched for symbol: IBM]
[2024-11-26 18:56:27,647: INFO: model_evaluation_mlflow: Real-time data scaled.]
[2024-11-26 18:56:27,647: INFO: stage05_model_evaluation: Testing model on real-time data...]
[2024-11-26 18:56:29,007: INFO: model_evaluation_mlflow: Real-time model testing complete.]
[2024-11-26 18:56:30,023: INFO: model_evaluation_mlflow: Testing complete. RMSE: 0.3591865693837794]
[2024-11-26 18:56:30,023: INFO: stage05_model_evaluation: Logging results to MLflow...]
[2024-11-26 18:56:36,611: INFO: builder_impl: Assets written to: C:\Users\Portable\AppData\Local\Temp\tmpcbsk5uh0\model\data\model\assets]
[2024-11-26 18:56:59,062: INFO: stage05_model_evaluation: Logged to MLflow successfully.]
[2024-11-26 18:56:59,062: INFO: main: >>> Stage Model Evaluation Stage Completed<<<]
